#!/bin/sh

# wrap-for-bin.sh: Template for git executable wrapper scripts
# to run test suite against sandbox, but with only bindir-installed
# executables in PATH.  The Makefile copies this into various
# files in bin-wrappers, substituting
# /home/manush/git-1.8.5.1 and test-path-utils.

GIT_EXEC_PATH='/home/manush/git-1.8.5.1'
if test -n "$NO_SET_GIT_TEMPLATE_DIR"
then
	unset GIT_TEMPLATE_DIR
else
	GIT_TEMPLATE_DIR='/home/manush/git-1.8.5.1/templates/blt'
	export GIT_TEMPLATE_DIR
fi
GITPERLLIB='/home/manush/git-1.8.5.1/perl/blib/lib'"${GITPERLLIB:+:$GITPERLLIB}"
GIT_TEXTDOMAINDIR='/home/manush/git-1.8.5.1/po/build/locale'
PATH='/home/manush/git-1.8.5.1/bin-wrappers:'"$PATH"
export GIT_EXEC_PATH GITPERLLIB PATH GIT_TEXTDOMAINDIR

exec "${GIT_EXEC_PATH}/test-path-utils" "$@"
